--- 
android: 
  components: 
    - build-tools-29.0.2
    - android-29
    - android-21
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-googleplayservices
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28
    - sys-img-armeabi-v7a-android-21
before_install: 
  - "yes | sdkmanager \"platforms;android-28\""
  - "chmod +x gradlew"
before_script: 
  - "echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -s \"768x1280\""
  - "emulator -avd test -no-audio -no-window &"
  - "adb wait-for-device"
  - "adb shell input keyevent 82 &"
deploy: 
  file: app/build/outputs/apk/release/app-release.apk
  provider: releases
  token: $GITHUB_KEY
  true: 
    tags: true
env: 
  global: 
    - MALLOC_ARENA_MAX=2
language: android
notifications: 
  email: 
    on_failure: always
    on_success: always
    recipients: 
      - wolf.adam94@gmail.com
script: "./gradlew :app:build :app:connectedDebugAndroidTest"
